### ISSUE TITLE
Question: how to generate log files?

### ISSUE THREAD

**Issue by melindaloubser1** [linguistica-uchicago/lxa5#17]
Hi,

An apology: my background is almost entirely in general linguistics; I am very new to the computational part.  I'm doing a presentation about linguistica and it would be really helpful to see what is "happening" behind the program i.e. what modifications to signatures were proposed, what description lengths were calculated - something like this older file:  http://people.cs.uchicago.edu/~jagoldsm/slides/2015-lxa-recomputation.pdf. Is it possible to generate a log file like this from within the linguistica CLI? If yes, how?

**Comment by jacksonllee** [comment]
Hi, sorry for the delay. The Linguistica 5 python library from this repo doesn't yet generate the detailed logs as Linguistica 4 did. We are porting the Lxa4 functionality to Lxa5 and adding new things from time to time, and hopefully we'll get to the logging output before too long..

**Comment by melindaloubser1** [comment]
Hi,

Thanks for getting back to me, that makes sense, sorry still learning how
these things work.


On Oct 6, 2017 3:47 PM, "Jackson L. Lee" <notifications@github.com> wrote:

Hi, sorry for the delay. The Linguistica 5 python library from this repo
doesn't yet generate the detailed logs as Linguistica 4 did. We are porting
the Lxa4 functionality to Lxa5 and adding new things from time to time, and
hopefully we'll get to the logging output before too long..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/linguistica-uchicago/lxa5/issues/17#issuecomment-334759635>,
or mute the thread
