### ISSUE TITLE
Running setup.py install for scipy... error

### ISSUE THREAD

**Issue by Gigageiger** [linguistica-uchicago/lxa5#20]
Hi. I've been trying to install Linguistica on Windows with `pip install linguistica`, but I keep getting the above error. After trying to find several missing files, the command terminal comes back with an error code 1. Even after successfully installing scipy beforehand, installing linguistica automatically uninstalls scipy and tries to install it again with setup.py, coming back the the error again... Is there a solution to this? Thanks.

**Comment by jacksonllee** [comment]
Hello, please try the following two commands:

1. `pip install -U pip` (to ensure `pip` is up-to-date)
2. `pip install scipy>=0.19.0,<=0.19.99` (that's the scipy version pinned for the linguistica 5.2.0 release) [EDIT 2018-10-11: more recent versions of scipy (currently v1.1.0) should also work] [EDIT 2018-10-12: linguistica >=5.2.1 has removed the scipy version number upper bound]

Hopefully everything goes with the above, and then please try `pip install linguistica` again.

**Comment by jacksonllee** [comment]
@IvanAlvarez lxa5 should also work with any recent versions of scipy (currently v1.1.0). (I've updated my comment above.) It looks like from your output that your system was trying to install scipy from the source `.tar.gz`, which involved the rather error-prone stage of wheel building. If you're on {mini,ana}conda, would something like `conda install scipy` work instead?

**Comment by IvanAlvarez** [comment]
Ah, I see. I think there might be an issue with detecting if valid dependencies are present. I can successfully install scipy (v1.1.0) via pip/conda, but when I try `pip install linguistica` it still attempts to pull various packages at specific releases, and install them from source:

```
Collecting networkx<=1.11.99,>=1.11 (from linguistica)
Collecting six<=1.10.99,>=1.10.0 (from linguistica)
Collecting scipy<=0.19.99,>=0.19.0 (from linguistica)
Collecting numpy<=1.12.99,>=1.12.1 (from linguistica)
Requirement already satisfied: decorator>=3.4.0 in ./anaconda3/lib/python3.7/site-packages (from networkx<=1.11.99,>=1.11->linguistica) (4.3.0)
Building wheels for collected packages: scipy, numpy
  Running setup.py bdist_wheel for scipy ... error
[...]
```

And it ends up with the same error I posted above.

**Comment by jacksonllee** [comment]
Gah, it looks like linguistica 5.2.0 has upper bounds for the version numbers of the dependencies, where scipy is restricted to be <= 0.19.99. Apparently, I already removed these upper bounds on the GitHub source code some time ago, but this update wasn't released on PyPI. I have just made a new release of linguistica (v5.2.1) on PyPI. `pip install -U linguistica` should now get you this latest lxa5. Please let me know if there are issues still.

**Comment by IvanAlvarez** [comment]
That worked a treat, thank you!
